#################################################################################
#                          *** datasetConfig.yaml ***                           #
#################################################################################



Thermal_TISR2024_Track2:
    origin: TISR2024_track2
    classes: 
        - mode
        - class
    preprocessings: # Must be list
        - Pass()


